# Generated by Django 4.0.6 on 2022-07-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('cantidad_mascotas', models.IntegerField(verbose_name='Cantidad de Mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idprod', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('nombprod', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('descripcion_prod', models.CharField(max_length=1000, verbose_name='Descripcion del producto')),
                ('stock', models.IntegerField(verbose_name='Stock del producto')),
            ],
        ),
    ]
