# Generated by Django 4.0.6 on 2022-07-15 00:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='idorden',
            field=models.CharField(default=app.models.random_string, max_length=10, primary_key=True, serialize=False, verbose_name='Numero de orden'),
        ),
    ]
