# Generated by Django 4.0.6 on 2022-07-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_compra_idorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
