# Generated by Django 4.0.6 on 2022-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_nomb_prod_compra_nombre_del_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='seguimiento',
            field=models.CharField(default='En preparación', max_length=50, null=True, verbose_name='Seguimiento'),
        ),
    ]
